### ISSUE TITLE
Support long service name display friendly ?

### ISSUE THREAD

**Issue by zxbu** [apache/skywalking-rocketbot-ui#102]
service名字太长的话，在trace页面，只能看到service的前几个字母，鼠标放上去也不会有提示，很难找某一个service。
（我英语不好，这句话太复杂了我不会用英语写，原谅我吧。如果哪位大神顺手帮我翻译一下，我会非常感谢的）

**Comment by wu-sheng** [comment]
English only

**Comment by wu-sheng** [comment]
English only

**Comment by wu-sheng** [comment]
This is Apache rule, not set by me.
