### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by coki230** [apache/skywalking-rocketbot-ui#103]

**Comment by JaredTan95** [comment]
What's the problem?

**Comment by coki230** [comment]
when i run the command "npm install", it give a error of "未找到导入的项目“D:\Microsoft.Cpp.Default.props”。"; can you give me some suggestions

**Comment by coki230** [comment]
by the way, i am java coder, so maybe the question is too stupid.

**Comment by coki230** [comment]
maybe i fix it, so i close it. i followed some vue coder's advice, which is use "cnpm install" instand of the "npm install"
