### ISSUE TITLE
about endpoint Selection box size issues

### ISSUE THREAD

**Issue by Stephen-sen** [apache/skywalking-rocketbot-ui#104]
I find when i endpoint name is to long，the name will hide many，led to，I don't know which endpoin I've select.could the Selection box a larger?
![TIM图片20190513182914](https://user-images.githubusercontent.com/3774605/57614922-07abc380-75ad-11e9-86e6-160b29eca378.png)

**Comment by Stephen-sen** [comment]
and Drill down function is very useful，hope ui support it

**Comment by wu-sheng** [comment]
Dripp down related to #62
