### ISSUE TITLE
Cache/Persist page query states

### ISSUE THREAD

**Issue by kezhenxu94** [apache/skywalking-rocketbot-ui#106]
![image](https://user-images.githubusercontent.com/15965696/57941526-c3e4f100-7901-11e9-8c62-e676568832a9.png)

The three dropdown boxes **Service**, **Instance**, and **Status**, as well as other query parameters such as **Endpoint Name**, **Trace ID**, Sorted property (duration/startTime), etc. are not cached locally (in browser), I try press **Search** button to **do the query again** but it sometimes failed (no effects), and I have to refresh the page (by Cmd+R or F5), and the query parameters are all gone that I have to re-select the parameters, it's sometimes annoying.

Same problem also exists in other tabs than **Trace**, it's not a severe problem but really effect user experience.

I can improve this if you've got no time to do this.

Thanks

**Comment by wu-sheng** [comment]
In ASF, you don't need permission, do it if it is improvement. Discuss when you are not certain it is the right direction or not.

**Comment by wu-sheng** [comment]
@kezhenxu94 Are you still doing this?

**Comment by kezhenxu94** [comment]
> @kezhenxu94 Are you still doing this?

No, I'm recently doing the agent reset, feel free to close or label "help wanted" or anything :)

**Comment by wu-sheng** [comment]
Move to 6.4.0 now.

**Comment by x22x22** [comment]
At http://122.112.182.72:8080/trace, I can't seem to reproduce this question. How can I reproduce this problem?

**Comment by x22x22** [comment]
> Move to 6.4.0 now.

At http://122.112.182.72:8080/trace, I can't seem to reproduce this question. How can I reproduce this problem?

**Comment by x22x22** [comment]
> ![image](https://user-images.githubusercontent.com/15965696/57941526-c3e4f100-7901-11e9-8c62-e676568832a9.png)
> 
> The three dropdown boxes **Service**, **Instance**, and **Status**, as well as other query parameters such as **Endpoint Name**, **Trace ID**, Sorted property (duration/startTime), etc. are not cached locally (in browser), I try press **Search** button to **do the query again** but it sometimes failed (no effects), and I have to refresh the page (by Cmd+R or F5), and the query parameters are all gone that I have to re-select the parameters, it's sometimes annoying.
> 
> Same problem also exists in other tabs than **Trace**, it's not a severe problem but really effect user experience.
> 
> I can improve this if you've got no time to do this.
> 
> Thanks

At http://122.112.182.72:8080/trace, I can't seem to reproduce this question. How can I reproduce this problem?

**Comment by kezhenxu94** [comment]
@x22x22 it's always reproducible, try to select some query criteria, e.g. choose a service, an instance, switch the sorting order to "startTime", and hit the refresh button of the browser, (or Ctrl-R or Command-R ) to refresh the webpage, all query criteria you selected will be back to defaults, I'd like them to be cached(e.g. in localStorage) and restored after refreshed

**Comment by x22x22** [comment]
> @x22x22 it's always reproducible, try to select some query criteria, e.g. choose a service, an instance, switch the sorting order to "startTime", and hit the refresh button of the browser, (or Ctrl-R or Command-R ) to refresh the webpage, all query criteria you selected will be back to defaults, I'd like them to be cached(e.g. in localStorage) and restored after refreshed

browser refresh after you want save all query criteria? including service name, instance name, track id, time sort, time range and other? and add a reset all criteria button?

**Comment by kezhenxu94** [comment]
> and add a reset all criteria button?

Nope, the restoration should be done in the background automatically (without hitting a button manually) if there are cached criteria, it's usual in many websites, if you're not sure, feel free to ask here before coding . 

- choose criteria 
- cache them
- refresh webpage 
- prefill the cached criteria

**Comment by x22x22** [comment]
> > and add a reset all criteria button?
> 
> Nope, the restoration should be done in the background automatically (without hitting a button manually) if there are cached criteria, it's usual in many websites, if you're not sure, feel free to ask here before coding .
> 
> * choose criteria
> * cache them
> * refresh webpage
> * prefill the cached criteria

I understand your needs, but I think adding a button that restores the default value will be more friendly.

**Comment by x22x22** [comment]
@kezhenxu94 
see https://github.com/apache/skywalking-rocketbot-ui/pull/150
