### ISSUE TITLE
Is it possible to have the function of Apdex

### ISSUE THREAD

**Issue by smooth00** [apache/skywalking-rocketbot-ui#117]
Skywalking is a wonderful product, but what a pity that I have not found the  Apdex (Application Performance Index).  We pretty need this function because we often use it to evaluate our software performance such as "satisified, tolerating, frustrated", etc. 
To make my description clear, in below is an example of our normal use:
![1](https://user-images.githubusercontent.com/43713947/59689445-3d7a4280-9212-11e9-910c-d0674a45be89.png)

**Comment by wu-sheng** [comment]
You could contribute Appdex(like CPM, p99 metrics function) to the SkyWalking, including OAL and UI. This is not a UI issue.
