### ISSUE TITLE
The topology map is not displayed

### ISSUE THREAD

**Issue by shook2012** [apache/skywalking-rocketbot-ui#134]
After running for a while, the topology map is not displayed. The front end reported the following error:
`index.ts:177 Uncaught (in promise) TypeError: Cannot read property 'value' of undefined
    at index.ts:177
(anonymous) @ index.ts:177
Promise.then (async)
p.dispatch @ vuex.esm.js:430
dispatch @ vuex.esm.js:322
n.<computed> @ vuex.esm.js:924
value @ topology.vue?b948:48
value @ topology.vue?b948:45
ne @ vue.runtime.esm.js:1854
jn @ vue.runtime.esm.js:4190
insert @ vue.runtime.esm.js:3132
D @ vue.runtime.esm.js:6307
(anonymous) @ vue.runtime.esm.js:6526
Pn.t._update @ vue.runtime.esm.js:3916
i @ vue.runtime.esm.js:4037
ei.get @ vue.runtime.esm.js:4440
ei @ vue.runtime.esm.js:4429
Ln @ vue.runtime.esm.js:4044
wi.$mount @ vue.runtime.esm.js:8373
cd49 @ main.ts:70
s @ bootstrap:78
0 @ bootstrap:151
s @ bootstrap:78
a @ bootstrap:45
(anonymous) @ bootstrap:151
(anonymous) @ bootstrap:151
`
The server interface returns normally.

**Comment by shook2012** [comment]
version: 6.3.0

**Comment by wu-sheng** [comment]
This means, backend is not healthy. Check the oap response.
