### ISSUE TITLE
Why not use the existing Ui component library?  Such as iview, element ui...

### ISSUE THREAD

**Issue by x22x22** [apache/skywalking-rocketbot-ui#151]
Why not use the existing Ui component library?  Such as iview, element ui...,thank you

**Comment by wu-sheng** [comment]
I think we are using ECharts today.

**Comment by wu-sheng** [comment]
@TinyAllen I think you could explain the design.

**Comment by x22x22** [comment]
> I think we are using ECharts today.

but ECharts is chart, not like [element ui](https://element.eleme.cn/#/zh-CN/component/installation)

**Comment by wu-sheng** [comment]
For other part, I don't know.

**Comment by TinyAllen** [comment]
x22x22 no using other library is for the dist package size minimization and thematic distinctness.
