### ISSUE TITLE
There is an extension function, hope the front end help

### ISSUE THREAD

**Issue by Indifer** [apache/skywalking-rocketbot-ui#162]
When skywalking is looking at the performance data of the 'endpoint' on the dashboard, it is not convenient and requires switching between each 'endpoint'.Feel the way 'cat' is presented is a little clearer.So I extended the back-end interface to implement a data presentation function like this, but with the help of the front end.

skywalking在看仪表盘看 ‘endpoint’ 性能数据的时候，其实并不方便，需要每个 ‘endpoint‘ 切换。感觉’cat‘的展现方式反而更清晰点。所以我对后端接口做了扩展，实现了类似这种数据展示功能，但是需要有前端配合，期望有人帮助一起实现。

**Comment by Indifer** [comment]
![image](https://user-images.githubusercontent.com/7918822/66379946-04482700-e9e9-11e9-82ac-19fda73ad611.png)

**Comment by wu-sheng** [comment]
I think you don't work in the right way. In the open source community, if you propose any change, you need to talk to the whole community about why, how and who will do that. 

In SkyWalking, we don't accept the requirement, we talk with contributors what they want to contribute, and whether it is good for the community public good. If YES, we work on the review and accept it if it is good enough.

So, I have to close this, no matter this is good or bad, we totally need you to do this in the right process.
