### ISSUE TITLE
NPM install reports this error

### ISSUE THREAD

**Issue by break60** [apache/skywalking-rocketbot-ui#170]
![image](https://user-images.githubusercontent.com/28628088/67669051-14ca3c80-f9ac-11e9-9d09-b1c4bc3341b4.png)

**Comment by wu-sheng** [comment]
Our CI is keeping running for every commit. I don't find the error. This is all master and PR related CI jobs, green all the time. https://builds.apache.org/blue/organizations/jenkins/skywalking-ci-it/activity
