### ISSUE TITLE
6.1.0 skywalking topology map

### ISSUE THREAD

**Issue by 653941214** [apache/skywalking-rocketbot-ui#172]
Only all services are displayed in the topology map. Why not filter an application?
![image](https://user-images.githubusercontent.com/48574114/67743527-e5720900-fa59-11e9-8ee6-c87b0be397bd.png)

**Comment by 653941214** [comment]
Several applications are monitored, and the topology map is crumpled together, and only all services are displayed here. Why don't all applications be listed in the drop-down list for selection?

**Comment by TinyAllen** [comment]
Filter applications feature has already done. but 6.1.0 doesn't include this feature.
![截屏2019-10-29下午4 01 39](https://user-images.githubusercontent.com/19775780/67748416-d7c28080-fa65-11e9-9ba1-09559ecfe03d.png)

**Comment by 653941214** [comment]
> Filter applications feature has already done. but 6.1.0 doesn't include this feature.
> ![截屏2019-10-29下午4 01 39](https://user-images.githubusercontent.com/19775780/67748416-d7c28080-fa65-11e9-9ba1-09559ecfe03d.png)
So do I need to use a higher version?

**Comment by 653941214** [comment]
So do I need to use a higher version?
