### ISSUE TITLE
Do you plan to support more external authentication? such as OIDC、OpenLDAP、etc

### ISSUE THREAD

**Issue by lusyoe** [apache/skywalking-rocketbot-ui#194]

**Comment by wu-sheng** [comment]
We don't support any authentication. And AKAIK, no committer is working on this.

**Comment by dagmom** [comment]
If i want to do this, oauth2 first.
I think we need create oauth2 client server module on main repository and UI go to auth server by client server.
@wu-sheng Help me review the proposal.

**Comment by wu-sheng** [comment]
This require UI and backend sides work, if you want to do so, provide a proposal in Google doc, send the copy to the maillist, and we should discuss it, and make the team review it.

**Comment by wu-sheng** [comment]
There are several design proposals, such as profiling or meter system.

**Comment by wu-sheng** [comment]
Rocketbot UI is replaced by the new [Booster UI](https://github.com/apache/skywalking-booster-ui) since 9.0.0 release.
