### ISSUE TITLE
Service dependency metrics compare

### ISSUE THREAD

**Issue by Fine0830** [apache/skywalking-rocketbot-ui#198]
add service dependency metrics(line of service topology) into the comparison entity list. As a result, you could compare one service A V.S. serviceA-call-serviceB metrics(client side).

**Comment by wu-sheng** [comment]
@Fine0830 Please submit the screenshot to make the description more clear.

**Comment by Fine0830** [comment]
![compare](https://user-images.githubusercontent.com/20871783/68951590-60c51000-07f9-11ea-9962-007873777af8.gif)
