### ISSUE TITLE
Sync timezone with oap server

### ISSUE THREAD

**Issue by zhengcan** [apache/skywalking-rocketbot-ui#213]
Currently, UI query data by using client timezone as default.
It really easy forgetting to adjust it to use server timezone.

I wish the UI could sync timezone setting with oap server automatically.
It could be a default setting.

Specially in skywalking docker image, the timezone is always UTC.

**Comment by wu-sheng** [comment]
Yea. @x22x22 should add this shortly.

**Comment by wu-sheng** [comment]
Could you submit issue to the main repo?

**Comment by x22x22** [comment]
@wu-sheng ok
