### ISSUE TITLE
Vue warn in development mode

### ISSUE THREAD

**Issue by leemove** [apache/skywalking-rocketbot-ui#230]
#229 

![IMG20191212_123643.png](https://tuchuang001.com/images/2019/12/12/IMG20191212_123643.png)

we can fix it by using a factory function to set the  default value.

**Comment by wu-sheng** [comment]
We can't see you screenshot.

**Comment by leemove** [comment]
[![IMG20191212-123643.png](https://i.postimg.cc/9F2gB1T7/IMG20191212-123643.png)](https://postimg.cc/t7rzq3Bq)

@wu-sheng
