### ISSUE TITLE
skywaling 7.0.0 profile analysis function ui error

### ISSUE THREAD

**Issue by tanks-oracle** [apache/skywalking-rocketbot-ui#283]
Uncaught (in promise) TypeError: Cannot read property 'id' of undefined
    at profile-store.ts:159

Uncaught (in promise) TypeError: Cannot read property 'getProfileAnalyze' of undefined
    at profile-store.ts:213

**Comment by wu-sheng** [comment]
How to re-produce this error?

**Comment by tanks-oracle** [comment]
pic：
https://raw.githubusercontent.com/tanks-oracle/saturn-config-center/master/error.png

**Comment by itdamo** [comment]
I'v meeted the same error.

**Comment by wu-sheng** [comment]
Fixed in the master already. Backend TTL issue caused this.
