### ISSUE TITLE
Missing relation scopes in alarm view

### ISSUE THREAD

**Issue by mrproliu** [apache/skywalking-rocketbot-ui#295]
Follow the https://github.com/apache/skywalking/pull/4769, the UI level currently misses the relation scopes items in the filter scope selection, and need to propagate the scope to the GraphQL query.
![image](https://user-images.githubusercontent.com/3417650/81536936-f7d0e600-939e-11ea-84ad-0145b7c05fdb.png)

**Comment by wu-sheng** [comment]
Provided in the master.
