### ISSUE TITLE
Proxy error: Could not proxy request /graphql from localhost:8080

### ISSUE THREAD

**Issue by karqical2016** [apache/skywalking-rocketbot-ui#299]
Proxy error: Could not proxy request /graphql from localhost:8080 to http://127.0.0.1:12800.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

it could not run this project on my computer,

**Comment by wu-sheng** [comment]
I run this in every day, all things are good. The UI requires the backend standing by.
