### ISSUE TITLE
ui 8.0 dashboard error

### ISSUE THREAD

**Issue by EtanYu** [apache/skywalking-rocketbot-ui#317]
I just download the 8.0 version from release page (https://downloads.apache.org/skywalking/8.0.0/apache-skywalking-apm-es7-8.0.0.tar.gz) and boot it up.but the UI is not working.
this is my info in chrome 
Unhandled promise rejection TypeError:e.map(...) flat is not a function
at a.value(dashboard.vue?e6d8:127)
at dashboard.vue?e6d8:116
...

can someone fix this error?

**Comment by wu-sheng** [comment]
Clean your browser local cache and your storage. This is a big upgrade, many things changed. 
Check our online demo. It is 8.0.0.

**Comment by kanouken** [comment]
> Clean your browser local cache and your storage. This is a big upgrade, many things changed.
> Check our online demo. It is 8.0.0.

not works
