### ISSUE TITLE
When you enter a Service filter that doesn't match anything, nothing changes on the page UI

### ISSUE THREAD

**Issue by Jtrust** [apache/skywalking-rocketbot-ui#327]
When you enter a Service filter that doesn't filter anything, nothing changes on the page UI

**Comment by wu-sheng** [comment]
Hi @Jtrust If you want to create an issue to track the issue, you could submit it to the main repo directly. Our release changelog is collected from there mostly. 
It is just a suggestion, it is fine to put in here.

**Comment by Fine0830** [comment]
@Jtrust When the service return `[]`, I found there is no problem here.
![test](https://user-images.githubusercontent.com/20871783/87264390-6ee73f80-c4f2-11ea-8593-d02bf8386c24.png)

**Comment by Jtrust** [comment]
For example, enter `projectd` first and then enter `test`, the case appeares.
![31594647806_ pic_hd](https://user-images.githubusercontent.com/21056967/87318703-49425080-c55b-11ea-85da-2e7159088ea0.jpg)
![21594647806_ pic_hd](https://user-images.githubusercontent.com/21056967/87319315-0cc32480-c55c-11ea-992d-d9b9dad750ba.jpg)
