### ISSUE TITLE
How to config instance Info in ui of v8.0

### ISSUE THREAD

**Issue by zhegexiaohuozi** [apache/skywalking-rocketbot-ui#335]
1. As title

2. Data of `JVM Memory` is often zero,such as
![image](https://user-images.githubusercontent.com/2982325/88381204-8a96f380-cdd8-11ea-903a-7d18ed368adb.png)

**Comment by wu-sheng** [comment]
1. Instance name could be set in many ways. Read agent set up document.
1. If data can't be reported no time such as performance issue of storage, then it is 0.

**Comment by zhegexiaohuozi** [comment]
@wu-sheng The frist question is not about agent.I mean how to show instance info in the UI 8.x，such as 
![image](https://user-images.githubusercontent.com/2982325/91002462-53974600-e601-11ea-9de2-778376d62bbe.png)
