### ISSUE TITLE
BUG: CLR Heap Memory displayed in byte unit

### ISSUE THREAD

**Issue by snakorse** [apache/skywalking-rocketbot-ui#341]
The `CLR Heap Memory` metrics in `Dashboard`->`Instance` tab currently is displayed in `byte` unit, it should be converted to the `MB` unit.

**Comment by wu-sheng** [comment]
Check the initial UI template yaml. You could change from there.

Ipen edit mode in UI, and update the config, then export. You should be able to have the updated yaml. Ping me if you need more help.

**Comment by snakorse** [comment]
Thanks, I changed the unit sucessfully according your reply, but I also think this should be set as default in the release build.

**Comment by wu-sheng** [comment]
Yes. But the pull request should be landed on the main repo. D you know the initial ui template yaml file?

**Comment by snakorse** [comment]
Oh, I found that file, I will make a PR in the main repo, thanks again.
