### ISSUE TITLE
Toplology View Render So Slowly

### ISSUE THREAD

**Issue by EvanLjp** [apache/skywalking-rocketbot-ui#343]
![image](https://user-images.githubusercontent.com/31562192/90584685-bfdf0780-e205-11ea-81c1-30e626aa2156.png)
when choose gateway ,there's going to be a lot of adjacency. the render time is so long

**Comment by wu-sheng** [comment]
Do you have the data? Have you checked whether this is not backend query issue? For the frontend, rendering node is not related to whethet it is a Gateway. Nothing is special.

**Comment by wu-sheng** [comment]
No update. Close for now.
