### ISSUE TITLE
Incompatible node-sass with node v12 (LTS) and v14

### ISSUE THREAD

**Issue by lujiajing1126** [apache/skywalking-rocketbot-ui#344]
I have tried to build this project with node v14 but unfortunately the `node-sass` used in the project is not compatible with the latest node version. Thus I switched to the LTS version, which is `v12.18.3`, but failed again.

After checking the document of [`node-sass`](https://www.npmjs.com/package/node-sass), I suppose the dependency should be upgraded to `v4.14.1` to be compatible with both v12 and v14.

Besides, vulnerabilities have been found with `npm audit`. I would like to create a PR to fix both these issues.

**Comment by kezhenxu94** [comment]
Should be dismissed by https://github.com/apache/skywalking-rocketbot-ui/pull/369
