### ISSUE TITLE
I find a problem in file of  localtime.ts

### ISSUE THREAD

**Issue by O-ll-O** [apache/skywalking-rocketbot-ui#351]
I found a problem in the queryOAPTimeInfo function of the file named localtime.ts,It is recommended to modify：
export const queryOAPTimeInfo = async () => {
  let utc = window.localStorage.getItem('utc');
  if (!utc ) {
    const res: AxiosResponse = await graph.query('queryOAPTimeInfo').params({});
    if (!res.data || !res.data.data || !res.data.data.getTimeInfo || !res.data.data.getTimeInfo.timezone) {
      setTimezoneOffset();
      return;
    }
    utc = res.data.data.getTimeInfo.timezone / 100 + '';
    window.localStorage.setItem('utc', utc);
  }
};

**Comment by wu-sheng** [comment]
Submit a pull request if you want to change or improve anything. Thanks.
