### ISSUE TITLE
Profile page usability issue 

### ISSUE THREAD

**Issue by xbkaishui** [apache/skywalking-rocketbot-ui#355]
For the profile Thread stack page， if the stack is too deep， can't show anything  in Thread stack column, can't scroll to right 
<img width="589" alt="屏幕快照 2020-09-13 下午7 48 19" src="https://user-images.githubusercontent.com/1477791/93017465-92fef400-f5fb-11ea-8cf1-c1943771063e.png">

**Comment by wu-sheng** [comment]
Have been fixed in the 8.1.0.

**Comment by xbkaishui** [comment]
No, I just used the latest version(8.1.0). can you double check it ?

**Comment by wu-sheng** [comment]
At least master supported this.
![image](https://user-images.githubusercontent.com/5441976/93019350-fb080700-f608-11ea-9923-11e3107d6925.png)

**Comment by xbkaishui** [comment]
Got it. thanks
