### ISSUE TITLE
No update of values in instance dropdown after selecting all services

### ISSUE THREAD

**Issue by Lukasz11111** [apache/skywalking-rocketbot-ui#356]
Steps to Reproduce:

1. In the trace tab, select any service (which has an instance)
2. Select "all" again in the service dropdown

Expected Result: 
There are no instances in the instance dropdown

Actual Result: 
The instance dropdown includes instances from the service selected in the first point

![Adnotacja 2020-09-28 100140](https://user-images.githubusercontent.com/48470313/94406169-e6cc1a00-0171-11eb-8565-f017188281e4.png)
![Adnotacja 2020-09-28 100159](https://user-images.githubusercontent.com/48470313/94406175-e92e7400-0171-11eb-8eb3-e1e8cc2845c1.png)
![Adnotacja 2020-09-28 100219](https://user-images.githubusercontent.com/48470313/94406185-eb90ce00-0171-11eb-96d7-e21b3ea97623.png)

**Comment by wu-sheng** [comment]
Could you try to fix this?

**Comment by Lukasz11111** [comment]
I can't, I'm just a junior tester

**Comment by wu-sheng** [comment]
Then, it will take time as this is not a serious bug. Some committers would choose when to fix this.
