### ISSUE TITLE
error: In a non-default topology view, when you hover over services, the inscription "Les Miserables" is added along with the name of the service

### ISSUE THREAD

**Issue by Lukasz11111** [apache/skywalking-rocketbot-ui#357]
Steps to Reproduce:
1. Go to topology
2. Select second view
3. Select service
4. Hover over services

Expected Result: 
You see service name
Actual Result: 
You see "Les Miserables" and service name
![Zrzut ekranu 2020-09-30 130247](https://user-images.githubusercontent.com/48470313/94679158-ee312600-031f-11eb-9dec-132021b20280.png)

**Comment by wu-sheng** [comment]
Yes, this exists for a long time, This is a bug, just as a low priority, haven't one to fix it yet. You are welcome to contribute the fix.

**Comment by zeaposs** [comment]
Question - are there any plans to modify the default echarts node tool tip formatting (color, name, value, in this case dash), or is this treated as non-issue for now ?

**Comment by wu-sheng** [comment]
Yes, this should be fixed. If you want to do this, please.
