### ISSUE TITLE
Going to the dashboard instance by topology in some service does not display the correct data

### ISSUE THREAD

**Issue by Lukasz11111** [apache/skywalking-rocketbot-ui#358]
Steps to Reproduce:
Go to topology
Select service
Enter dashboard instance by service

Expected Result:
There should be charts with data in the dashboard
Actual Result:
Charts do not contain data (comparison with charts from the dashboard)
![Zrzut ekranu 2020-10-01 104114](https://user-images.githubusercontent.com/48470313/94787483-a7e8cf00-03d2-11eb-9ae1-dfc169a6e6b6.png)
![Zrzut ekranu 2020-10-01 104158](https://user-images.githubusercontent.com/48470313/94787550-bdf68f80-03d2-11eb-8ed1-007444624024.png)
![Zrzut ekranu 2020-10-01 104226](https://user-images.githubusercontent.com/48470313/94787608-d1095f80-03d2-11eb-9384-b49bf48b4e6c.png)

**Comment by wu-sheng** [comment]
@Fine0830 I think we are using the wrong service name. This variable seems from the dashboard page, rather than the real selected service.

![image](https://user-images.githubusercontent.com/5441976/94788241-e350c100-0405-11eb-9370-ad398743e874.png)

**Comment by wu-sheng** [comment]
@Lukasz11111  which version are you using?

**Comment by Lukasz11111** [comment]
version 8.1. The bug is repeatable on your demo

**Comment by wu-sheng** [comment]
Yes, confirmed.

**Comment by Fine0830** [comment]
The issue was fixed, please check. https://github.com/apache/skywalking-rocketbot-ui/pull/359
