### ISSUE TITLE
Data loading error caused by switching between dashboard and topology

### ISSUE THREAD

**Issue by Lukasz11111** [apache/skywalking-rocketbot-ui#360]
Steps to Reproduce:
Go to Dashboard
Choose not the first tab
Go to topology
Select service

Expected Result:
Charts should appear in serviceDetail
Actual Result:
Charts are not loading

Enter dashboard api by service

Expected Result:
There should be charts with data in the dashboard
Actual Result:
Charts are not loading
![image](https://user-images.githubusercontent.com/48470313/94902664-d9c46900-0498-11eb-9dc4-adc79bed07bc.png)
![image](https://user-images.githubusercontent.com/48470313/94902711-ec3ea280-0498-11eb-9c00-a8e0e59ca3c0.png)
![image](https://user-images.githubusercontent.com/48470313/94902745-fb255500-0498-11eb-9746-7b0f70671697.png)

**Comment by wu-sheng** [comment]
This is not an issue. Please understand the page first.
