### ISSUE TITLE
The chart legend overlaps the data

### ISSUE THREAD

**Issue by Lukasz11111** [apache/skywalking-rocketbot-ui#361]
Steps to Reproduce:
Go to Dashboard
Select APM tab
Select instance

Expected Result:
Charts contain a legend that does not overlap the data
Actual Result:
In some charts, the legend covers some of the data

![image](https://user-images.githubusercontent.com/48470313/94903874-b995a980-049a-11eb-96a3-9f3d58ab641c.png)

**Comment by wu-sheng** [comment]
Fixed already.
