### ISSUE TITLE
Too many decimal places in the chart data

### ISSUE THREAD

**Issue by Lukasz11111** [apache/skywalking-rocketbot-ui#362]
Steps to Reproduce:
Go to Dashboard
Select APM tab
Select instance

Expected Result:
The data from the charts will contain a limited number of decimal places
Actual Result:
There are too many decimal places in the JVM Memory (Java Service) chart

![image](https://user-images.githubusercontent.com/48470313/94904754-1776c100-049c-11eb-9110-a74dec48294e.png)

**Comment by wu-sheng** [comment]
Right now, it keeps what it is. We don't provide the precision yet.
