### ISSUE TITLE
question: is there a UI and skywalking version mapping table?

### ISSUE THREAD

**Issue by worldwalk** [apache/skywalking-rocketbot-ui#364]
such as skywalking v6.3.0, can it use UI v7.0.0 or v8.0.0 ?  thanks!

**Comment by wu-sheng** [comment]
No, we don't recommend it in this way. So, we don't provide the mapping table. Please use the same version.
Note, even the agent is not compatible between 6.3.0 agent(<8.0) and 8.0+ backend/UI.
