### ISSUE TITLE
Magic strings from selecting date to constants

### ISSUE THREAD

**Issue by masterxxo** [apache/skywalking-rocketbot-ui#371]
I was working on my own form and I found magic strings in some files. It can be moved to constants. 
Below I'm putting an example. I think the constat.ts file can be moved to the main directory or to the utils directory because keeping it in views directory is a little bit confusing sometimes.

```javascript
export enum TimeType {
  MINUTE_TIME = 'MINUTE',
  HOUR_TIME = 'HOUR',
  DAY_TIME = 'DAY',
}
```

**Comment by wu-sheng** [comment]
@TinyAllen Any preference? I think you put the codes originally.

**Comment by masterxxo** [comment]
I can prepare a pull request with this changes if you want. Then you can review it and decide what to do with it.

**Comment by TinyAllen** [comment]
@masterxxo just do it 😊  l agree that using the constat.ts file, and move it to the main directory path.
