### ISSUE TITLE
Problem with removing tags in trace

### ISSUE THREAD

**Issue by Lukasz11111** [apache/skywalking-rocketbot-ui#376]
Go to trace in apm 8.2
Enter the name of the tag. Confirm with enter
Click on search
Remove a tag by clicking on the cross on it
![image](https://user-images.githubusercontent.com/48470313/100199614-b7c9ee80-2efd-11eb-8958-dfccf5b30a94.png)
The tag will come back after reloading the page

**Comment by wu-sheng** [comment]
Yes, this is a bug. Click the `clear` for now.

**Comment by Jtrust** [comment]
![test](https://user-images.githubusercontent.com/21056967/100265705-9ca5c000-2f8b-11eb-96f5-b9f37f509d5b.gif)
Is it a step like this? But I didn't reproduce the bug

**Comment by wu-sheng** [comment]
Use `key=value`. I think only a legal format tag could trigger this bug.

**Comment by Lukasz11111** [comment]
> Is it a step like this? But I didn't reproduce the bug
> ![test](https://user-images.githubusercontent.com/21056967/100265705-9ca5c000-2f8b-11eb-96f5-b9f37f509d5b.gif)

You don't click on search btn
![20201126_085507](https://user-images.githubusercontent.com/48470313/100322997-5a997000-2fc5-11eb-9409-de1729cb9052.gif)

**Comment by Fine0830** [comment]
Fixed this in https://github.com/apache/skywalking-rocketbot-ui/pull/386
