### ISSUE TITLE
After starting 'auto' in the dashboard, the legends from the observations are marked again

### ISSUE THREAD

**Issue by Lukasz11111** [apache/skywalking-rocketbot-ui#379]
![image](https://user-images.githubusercontent.com/48470313/100202545-bdc1ce80-2f01-11eb-98f1-22d7f2ecf87c.png)
![image](https://user-images.githubusercontent.com/48470313/100202627-db8f3380-2f01-11eb-9f8f-1fa5281008c2.png)

**Comment by wu-sheng** [comment]
Yes, this wouldn't be kept for now.
