### ISSUE TITLE
Entering the value -1 in the dashboard in the tab where there are some charts in auto reload makes the time start to move back

### ISSUE THREAD

**Issue by Lukasz11111** [apache/skywalking-rocketbot-ui#380]
This error does not matter much, I cannot imagine that someone who does not want to break the application could cause it

![20201125_100516](https://user-images.githubusercontent.com/48470313/100205807-df24b980-2f05-11eb-9813-c2dc65e07845.gif)

**Comment by wu-sheng** [comment]
This is a low priority bug, if anyone has an interest, welcome to submit a pull request.
