### ISSUE TITLE
The date does not refresh after clicking the browser refresh button

### ISSUE THREAD

**Issue by mritd** [apache/skywalking-rocketbot-ui#385]
### OS ENV

OS: macOS 10.15.7 (19H15)
Browser: Chrome 86.0.4240.198
Skwalking-UI: 8.2.0

### Description

When I click the browser refresh button or use `Command+R` to refresh the page, the date selection control of Skywalking UI does not refresh.

![image](https://user-images.githubusercontent.com/13043245/100430290-8ace3500-30d1-11eb-963e-cdcd3da9b82a.png)

**Comment by wu-sheng** [comment]
Yes. All dates would not be refreshed. Use the `fresh` button on the right top.

**Comment by mritd** [comment]
@wu-sheng I tried to use the auto-refresh button on the UI, but the F12 control is too far from any graphql request.

![image](https://user-images.githubusercontent.com/13043245/100431144-b43b9080-30d2-11eb-9fb3-4636c4c8d6d8.png)

**Comment by wu-sheng** [comment]
Auto is for dashboard, not trace query.

**Comment by mritd** [comment]
@wu-sheng So, for trace I expect to see the latest status in real time; but the browser refresh button does not work.......

**Comment by wu-sheng** [comment]
You should click `reload`.

**Comment by mritd** [comment]
**If you mean clicking this button, sorry it doesn’t work either...no request**

![image](https://user-images.githubusercontent.com/13043245/100432074-0630e600-30d4-11eb-98c8-8d5d273cdc0c.png)

**Comment by wu-sheng** [comment]
What request? It just updates the time range. There is no such thing like query the latest traces. We don't provide that today.

**Comment by mritd** [comment]
I just want to view the latest trace in real time, but now it seems there is no way.

**Comment by wu-sheng** [comment]
No, there isn't.

**Comment by wu-sheng** [comment]
Reload/refresh/clear are for reset the time range to the latest based on your browser(local time), but no query on the trace page, unless you click by yourself.

**Comment by mritd** [comment]
Okay, got it.👌
