### ISSUE TITLE
Questions on log tab

### ISSUE THREAD

**Issue by bond-** [apache/skywalking-rocketbot-ui#416]
- What's the use of the log tab?
- When I send the trace logs via Java agent where do they end up and how can I see them on the UI?

![image](https://user-images.githubusercontent.com/776647/105537378-d65f2280-5cbf-11eb-924c-d590d2971a27.png)

**Comment by wu-sheng** [comment]
Hi, the log tab currently is for browser monitoring. The java log collection will be released on next 8.4.0.
Follow our twitter ASFSkyWalking for quick announcement.
