### ISSUE TITLE
How to Disable the HTTP TRACE Method on skywalking-ui

### ISSUE THREAD

**Issue by coolbeevip** [apache/skywalking-rocketbot-ui#437]
environment: apache/skywalking-ui:8.1.0 with docker

My customer security department asked to disable the TRACE method, can you give me some suggestions?

**Comment by wu-sheng** [comment]
Your customer, your service. Please don't mix the community with your commercial service.

**Comment by coolbeevip** [comment]
Thank you for your suggestion, please relax

**Comment by coolbeevip** [comment]
Thank you for your suggestion, please relax
