### ISSUE TITLE
The footer and topology group is shaded when the topology radiation is displayed.

### ISSUE THREAD

**Issue by heihaozi** [apache/skywalking-rocketbot-ui#445]
The footer and topology group is shaded when the topology radiation is displayed. 

As shown below:

![](https://user-images.githubusercontent.com/2956927/111252464-274e2000-864c-11eb-9913-5dabd8bfab1a.jpg)

**Comment by heihaozi** [comment]
When the problem is fixed, the footer and topology group is displayed like this:

![](https://user-images.githubusercontent.com/2956927/111253522-48b00b80-864e-11eb-9554-1e4cdf4b3194.jpg)

**Comment by heihaozi** [comment]
My monitor is 23.8 inches. In Firefox 86.0.1 and Chrome 89.0.4389.82, the footer and topology group are all blocked.

By the way, the version of Skywalking is 8.2.0.

**Comment by wu-sheng** [comment]
Let's wait for the review.

**Comment by Fine0830** [comment]
The footer has been shaded from pop-up window in latest version. The group works well. That is fine to add `z-index` for them.
