### ISSUE TITLE
When the topology radiation chart is displayed, the corresponding button should be highlighted.

### ISSUE THREAD

**Issue by heihaozi** [apache/skywalking-rocketbot-ui#447]
When the topological radiation diagram is displayed, there is no change to the corresponding button.

As shown below:

![](https://user-images.githubusercontent.com/2956927/111559877-4f648d00-87cc-11eb-858d-894b04d81488.jpg)

For a better user experience, the corresponding button should be highlighted.

**Comment by wu-sheng** [comment]
@heihaozi you should consider updating the main repo's UI submodule, and sync the changelog. There are several commits landed here made by you and other contributors.

**Comment by heihaozi** [comment]
> 
> 
> @heihaozi you should consider updating the main repo's UI submodule, and sync the changelog. There are several commits landed here made by you and other contributors.

How to update the main repo's UI submodule? I still don't know very well, please give me more tips.

What you mean by sync the changelog, is it to resubmit the PR for [CHANGES.md](https://github.com/apache/skywalking/blob/master/CHANGES.md)?

**Comment by wu-sheng** [comment]
Read git submodule document, then you will notice we are using that to link main repo and rocketbot-ui repo.
Changelog is the file you linked, once you update the submodule, you should update all related changes in that file.

**Comment by heihaozi** [comment]
I have updated main repo's UI submodule in [my branch](https://github.com/heihaozi/skywalking/commit/268dacc8d29d61fb983bd660dfc6ec1a7558947f). As shown below:

![](https://user-images.githubusercontent.com/2956927/111622920-b57cfe80-8824-11eb-8ae8-b0b60c4b6ae5.png)

But I only know what I modified, and there is no way to update the change log including all other contributors.

**Comment by wu-sheng** [comment]
Check your local git changes, you could find the commit id change(from...to). Then you could have full list of changes here, https://github.com/apache/skywalking-rocketbot-ui/commits/master

**Comment by heihaozi** [comment]
This is a good idea, I have found it.
