### ISSUE TITLE
profile tab not show complete thread stack 

### ISSUE THREAD

**Issue by ZhangShangyu** [apache/skywalking-rocketbot-ui#449]
hi,  I am trying skywalking profile demo, but frontend not show the complete thread stack,  seems the thread stack is too long and cannot scroll
![image](https://user-images.githubusercontent.com/15957047/111571681-23540680-87e2-11eb-8d0a-d8b0b19c842d.png)

**Comment by Fine0830** [comment]
You can use the icon to change this width.
![test](https://user-images.githubusercontent.com/20871783/111579491-112d9480-87f1-11eb-9943-c3b60abde11f.jpeg)
![12](https://user-images.githubusercontent.com/20871783/111579524-1f7bb080-87f1-11eb-94ec-758a71651cdf.png)
