### ISSUE TITLE
Topology optimization of two services that call each other. 

### ISSUE THREAD

**Issue by heihaozi** [apache/skywalking-rocketbot-ui#453]
In actual business scenarios, there will be situations where two services call each other (not a cyclic call, they are different endpoints of the services).

 In the topology, it is displayed like this: 

![20210325112817](https://user-images.githubusercontent.com/2956927/112428234-d2aa5380-8d75-11eb-8927-2669a739cf1f.jpg)

In fact, the two lines overlap, and the points at the midpoints of the lines overlap.

**Comment by wu-sheng** [comment]
Are you planning to separate them?

**Comment by heihaozi** [comment]
> 
> 
> Are you planning to separate them?

Yes, I do.
