### ISSUE TITLE
Cannot distinguish between upstream and downstream services. 

### ISSUE THREAD

**Issue by heihaozi** [apache/skywalking-rocketbot-ui#467]
When selecting a service in the topology diagram, all the services are displayed together.

 As shown below: 

![20210414180046](https://user-images.githubusercontent.com/2956927/114824679-d1f66180-9df7-11eb-993a-5b9d3f355908.jpg)

Cannot distinguish between upstream and downstream services.

**Comment by heihaozi** [comment]
I have an idea to better distinguish upstream and downstream services. 

As shown below:

![20210414175852](https://user-images.githubusercontent.com/2956927/114825337-acb62300-9df8-11eb-826e-b42d3c8306f3.jpg)

**Comment by wu-sheng** [comment]
It is impossible. When you face a real topology, it is not like this.

**Comment by wu-sheng** [comment]
This is only possible as one service topology.

**Comment by heihaozi** [comment]
In response to this idea, I submitted a [PR](https://github.com/apache/skywalking-rocketbot-ui/pull/468)。
