### ISSUE TITLE
When creating service groups in the topology, it is better if the service names are sorted. 

### ISSUE THREAD

**Issue by heihaozi** [apache/skywalking-rocketbot-ui#477]
I found that when creating service groups in the topology, the service names are out of order. 

As shown below: 

![20210419143156](https://user-images.githubusercontent.com/2956927/115192275-2d3c9280-a11d-11eb-865c-69ca8d4e6418.jpg)

When there are more services, it is more difficult to find the service you are looking for. 

It is better if the service names are sorted. 

As shown below: 

![20210419143422](https://user-images.githubusercontent.com/2956927/115192431-6117b800-a11d-11eb-9221-e1444a8e3996.jpg)

**Comment by wu-sheng** [comment]
@heihaozi You should update the submodule of the main repo. And update the changes.md

**Comment by heihaozi** [comment]
> 
> 
> @heihaozi You should update the submodule of the main repo. And update the changes.md

ok, I will update as soon as possible.

**Comment by heihaozi** [comment]
It looks like the update is complete, and I don’t need to do anything.

**Comment by Fine0830** [comment]
> It looks like the update is complete, and I don’t need to do anything.

You should update the submodule of the main repo, like https://github.com/apache/skywalking/pull/6793

**Comment by wu-sheng** [comment]
> It looks like the update is complete, and I don’t need to do anything.

I did for you last time. There are 4 days gap.

**Comment by heihaozi** [comment]
> 
> 
> > It looks like the update is complete, and I don’t need to do anything.
> 
> You should update the submodule of the main repo, like [apache/skywalking#6793](https://github.com/apache/skywalking/pull/6793)

ok, I will update it next time.

**Comment by heihaozi** [comment]
> 
> 
> > It looks like the update is complete, and I don’t need to do anything.
> 
> I did for you last time. There are 4 days gap.

Sorry, I didn't see your reply in time.
