### ISSUE TITLE
After changing the durationTime, the topology shows the default again. 

### ISSUE THREAD

**Issue by heihaozi** [apache/skywalking-rocketbot-ui#489]
After changing the durationTime, the topology again displays all the services of the first group by default. 
I think it should show the topological of the group or service originally selected. 
![](https://user-images.githubusercontent.com/2956927/117262796-39964e80-ae84-11eb-83f9-f3b27ab1d6ab.png)

**Comment by wu-sheng** [comment]
Sync the main repo if you like.

**Comment by heihaozi** [comment]
> 
> 
> Sync the main repo if you like.

Okay, thanks for the reminder.
