### ISSUE TITLE
Log time selection occlusion

### ISSUE THREAD

**Issue by yang-dong-dong** [apache/skywalking-rocketbot-ui#493]
Log time selection occlusion

google chrome :  90.0.4430.93
skywalking-rocketbot-ui : docker ui 8.5.0

![image](https://user-images.githubusercontent.com/20069609/118445463-0de75400-b721-11eb-8478-1ffb4420331b.png)

**Comment by Fine0830** [comment]
The question is how to reproduce?

**Comment by yang-dong-dong** [comment]
![image](https://user-images.githubusercontent.com/20069609/118448048-10977880-b724-11eb-95ce-2d2896460c67.png)
