### ISSUE TITLE
Cannot read property 'serviceGroup' of undefined

### ISSUE THREAD

**Issue by tyunh** [apache/skywalking-rocketbot-ui#506]
version: 8.6.0 
storage: mysql

nginx conf
```
server {
        listen       80;
        server_name  sky.tangyh.top;
        underscores_in_headers on;

        location / {
            proxy_pass http://39.108.109.234:18080;
        }
}
```
1、 Nginx proxy access UI error

Google browser access [sky ui](http://39.108.109.234:18080) normal， but access  [sky ui](http://sky.tangyh.top) error .

![image](https://user-images.githubusercontent.com/8497919/121620749-7239d100-ca9d-11eb-80c2-ddd03366f346.png)

2、Browser compatibility issues

Google browser access [sky ui](http://sky.tangyh.top) normal , but edge ie  access error

**Comment by tyunh** [comment]
1、用谷歌浏览器 使用nginx 代理访问UI报错，直接ip：端口访问正常
2、edge ie 360 等浏览器访问报错

8.6.0 版本 ，mysql 存储

**Comment by wu-sheng** [comment]
Your private demo name, your responsibility. You can see our demo is working in the domain name already.

**Comment by tyunh** [comment]
Please provide your nginx agent configuration and documentation。

麻烦提供你们nginx代理的配置方式 和 相关文档。

**Comment by wu-sheng** [comment]
This is not a community thing. Sorry. Those deployments are on private/sponsored infrastructure. We can't open it.

**Comment by wu-sheng** [comment]
Demo, and real env deployment, are for users' review. But sponsor's engineer is working on this. And this is not a part of open resource or even it is not a part of SkyWalking open source projects. You only could take it as a reference.
And considering security issue, this should not be open too. Sorry.

**Comment by Rwing** [comment]
I had the same problem in v8.6.0 now.
And I reinstall a v8.5.0 everthing is ok.
I install sw with helm, the only difference between them is the version number

```
helm install "skywalking" skywalking -n "skywalking" \
  --set oap.image.tag=8.6.0-es7 \
  --set oap.storageType=elasticsearch7 \
  --set ui.image.tag=8.6.0 \
  --set elasticsearch.imageTag=7.5.1
```
```
helm install "skywalking" skywalking -n "skywalking" \
  --set oap.image.tag=8.5.0-es7 \
  --set oap.storageType=elasticsearch7 \
  --set ui.image.tag=8.5.0 \
  --set elasticsearch.imageTag=7.5.1
```

**Comment by Rwing** [comment]
Maybe we need to reopen this issue and double check it

**Comment by Rwing** [comment]
@wu-sheng

**Comment by wu-sheng** [comment]
@Rwing I have been very clear about this last time. You are setting a proxy on your own, it is not community's scope anymore.

**Comment by Rwing** [comment]
@wu-sheng Maybe I didn't make myself clear earlier.
I mean, I got this error on my first installation, I wasn't using a proxy or a domain name.
and I guess maybe everyone who installed the 8.6.0 version for the first time encountered this error.
The team members can easily reproduce the problem just use above command:
```
helm install "skywalking" skywalking -n "skywalking" \
  --set oap.image.tag=8.6.0-es7 \
  --set oap.storageType=elasticsearch7 \
  --set ui.image.tag=8.6.0 \
  --set elasticsearch.imageTag=7.5.1
```

**Comment by wu-sheng** [comment]
If you face anything new, submit a new issue rather than jumping in an irrelevant issue. 
But you also should know, we run helm installation every time, https://github.com/apache/skywalking/blob/master/.github/workflows/e2e.istio.yaml#L102-L116. It has confirm every commit id and release are good to run.
