### ISSUE TITLE
Allow specifies the ui site's http path

### ISSUE THREAD

**Issue by Rwing** [apache/skywalking-rocketbot-ui#507]
In reverse proxy case, the skywalking ui maybe mapped to http://example.com/skywalking-ui, so the correct css/js url is /skywalking-ui/foo.js not /foo.js.

if allow specifies the ui site's http path, then this problem can be solved
like as Consul's ui parameter
https://www.consul.io/docs/agent/options#ui_config_content_path

**Comment by wu-sheng** [comment]
You could follow #430, AFAIK, it is not working as expected.
