### ISSUE TITLE
log query bug?

### ISSUE THREAD

**Issue by wtjperi2003** [apache/skywalking-rocketbot-ui#516]
keyword search is not working.
![issuse](https://user-images.githubusercontent.com/10322892/124902233-54687900-e015-11eb-8eb7-5d231d629955.jpg)

**Comment by wu-sheng** [comment]
It seems a bug. @Fine0830 Could you recheck?

**Comment by Fine0830** [comment]
> It seems a bug. @Fine0830 Could you recheck?

Checked. It’s a bug.

**Comment by Fine0830** [comment]
I've rechecked. There is no bugs.
I![2](https://user-images.githubusercontent.com/20871783/125013656-c9cc5c00-e09e-11eb-8c1c-15dfbe5f2c98.png) no bugs.
![1](https://user-images.githubusercontent.com/20871783/125013650-c8029880-e09e-11eb-840e-0c8312aaaa94.png)

**Comment by cflhandsome** [comment]
need to press Enter...

**Comment by Fine0830** [comment]
Yep.
