### ISSUE TITLE
service出现重复的service名称

### ISSUE THREAD

**Issue by yybirdcf** [apache/skywalking-rocketbot-ui#520]
使用过程中发现service列表会出现重复的情况，具体如下图

![image](https://user-images.githubusercontent.com/1823054/126961022-bd8247ca-58da-4ba7-aedc-391b15e7ea3b.png)

![image](https://user-images.githubusercontent.com/1823054/126961200-2135e663-28f4-45f5-8dfd-8aa5be78c02c.png)

**Comment by wu-sheng** [comment]
Please use English, we are facing global users.
This is caused by your ElasticSearch performance issue. There are many similar discussion in the main repo.
