### ISSUE TITLE
In the trace panel, select service from the drop-down box, and click invalid when search

### ISSUE THREAD

**Issue by yybirdcf** [apache/skywalking-rocketbot-ui#521]
I clone code from master, but select service from drop-down box still invalid when search 

![image](https://user-images.githubusercontent.com/1823054/127131866-c3b52949-7862-4cb5-9905-e4ba6a37530e.png)

**Comment by wu-sheng** [comment]
![image](https://user-images.githubusercontent.com/5441976/127157514-c8ac3643-bfc0-4686-8e64-58709cea8ec9.png)

It works at the demo side.

**Comment by PythonWongXb** [comment]
**Error Reason: the same key in dataList.**

报出的错误的原因是重复的key，直接导致了前端内存泄漏。

两个方案
前端修改：修改循环渲染中的index值
后端修改：不要生成重复的key值
