### ISSUE TITLE
`Response Time Percentile ( ms )` does not change when click `Detect Point`

### ISSUE THREAD

**Issue by yaojingguo** [apache/skywalking-rocketbot-ui#526]
Environment:
- SkyWalking 8.4.0
- macOS 10.15.5
- Oracle JDK 1.8.0_162
- Chrome Version 92.0.4515.131 (Official Build) (x86_64)

When I first clicked the circle, the metrics for the server detect point was displayed:

<img width="897" alt="截屏2021-08-10 下午9 19 34" src="https://user-images.githubusercontent.com/516386/128874272-e80fe412-d0cb-406c-9d27-61d46f36441c.png">

Then I clicked `Client` detect point, the first free metrics changed. But `Response Time Percentile ( ms )` did not change.

<img width="900" alt="截屏2021-08-10 下午9 19 52" src="https://user-images.githubusercontent.com/516386/128874280-b76c69af-9e42-477f-82c5-f06d29f3d84b.png">

**Comment by wu-sheng** [comment]
I checked, it changes normally on the demo env.

**Comment by yaojingguo** [comment]
Thanks. We will wait for the 8.8.0 release.
