### ISSUE TITLE
日志页面的问题

### ISSUE THREAD

**Issue by wtjperi2003** [apache/skywalking-rocketbot-ui#533]
能不能把内容这一列，直接显示出来，每次点击打开弹窗，非常的麻烦，而且很多时候日志是上下一起看的，最好是直接显示，多了换行就好，行否？

**Comment by wu-sheng** [comment]
All discussion should be in English. And SkyWalking maintainers are not accepting tasks. We expect everyone to contribute feature and improvements back. If this is something you want to contribute, we are glad to evaluate and share what we think.
