### ISSUE TITLE
关于skywalkingUI log页面宽度的小问题 

### ISSUE THREAD

**Issue by GuoRanYiMao** [apache/skywalking-rocketbot-ui#534]
直接上图吧 
![image](https://user-images.githubusercontent.com/6648688/131610818-162e87c3-e02d-473b-9a62-13dae005942e.png)

就像这样
![image](https://user-images.githubusercontent.com/6648688/131611082-6b983558-43fe-41ad-9236-2b39c6aaa7f7.png)

**Comment by wu-sheng** [comment]
All issues should be in English.
