### ISSUE TITLE
there are some probrem bout skywalkingUI log page

### ISSUE THREAD

**Issue by GuoRanYiMao** [apache/skywalking-rocketbot-ui#535]
please look at images
![image](https://user-images.githubusercontent.com/6648688/131612257-e82b1456-efd5-4be1-9647-0d38137977b8.png)

like this
![image](https://user-images.githubusercontent.com/6648688/131612442-4efda557-e8e1-47c2-9af0-94af0d3bd699.png)

**Comment by wu-sheng** [comment]
The type seems TEXT, if there is contributor wants to contribute, we are willing to accept.
The open source project depends on you all.

**Comment by GuoRanYiMao** [comment]
got it , da lao

**Comment by GuoRanYiMao** [comment]
got it , dalao

**Comment by wu-sheng** [comment]
Rocketbot UI is replaced by the new [Booster UI](https://github.com/apache/skywalking-booster-ui) since 9.0.0 release.
