### ISSUE TITLE
[Question]When I add a new children dashBoard in dolphinscheduler.yml,it  doesn't take effect after i restart the skywalking-webapp(I have emptied the browser cache and made sure the local-endpoint exists)

### ISSUE THREAD

**Issue by Linkaiup** [apache/skywalking-rocketbot-ui#540]
**Search before asking**
I had searched in the issues and found no similar feature requirement.
https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue+skywalking

**What happened**

I add a child dashboard in the ${SKYWALKING_HOME}/config/ui-initialized-templates/dolphinscheduler.yml

```
{
              "name":"Worker Task",
              "children":[
                {
                  "width":3,
                  "title":"AbstractTask handle Load",
                  "height":350,
                  "entityType":"Endpoint",
                  "independentSelector":true,
                  "metricType":"REGULAR_VALUE",
                  "metricName":"endpoint_cpm",
                  "queryMetricType":"readMetricsValues",
                  "chartType":"ChartLine",
                  "currentService":"dolphinscheduler::worker-server",
                  "currentEndpoint":"worker/SHELL/handle"
                }
}
```

Then I make sure i have the local endpoint that i want to watch
![image](https://user-images.githubusercontent.com/25237367/133883239-5863419a-ccd2-4d1a-ae00-9c897a49a7b7.png)

But the web ui still doesn't take effect
![image](https://user-images.githubusercontent.com/25237367/133883284-6fe99fe3-0aa2-4a96-8902-3dc487428069.png)

**DolphinScheduler Version**
1.3.8-release

Additional context
No response

**Comment by wu-sheng** [comment]
This is a question, please move to SkyWalking discussion. https://github.com/apache/skywalking/discussions

**Comment by Linkaiup** [comment]
Thanks for your&nbsp;advice.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/skywalking-rocketbot-ui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月18日(星期六) 下午5:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/skywalking-rocketbot-ui] [Question]When I add a new children dashBoard in dolphinscheduler.yml,it  doesn't take effect after i restart the skywalking-webapp(I have emptied the browser cache and made sure the local-endpoint exists) (#540)





 
This is a question, please move to SkyWalking discussion. https://github.com/apache/skywalking/discussions
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
