### ISSUE TITLE
there is a paging youprobrem about skywalkingUI log page

### ISSUE THREAD

**Issue by anjoy8** [apache/skywalking-rocketbot-ui#560]
hi ,I found a small problem.
On the log page, the pagesize parameter of graph paging is 35,but the paging page number seems to be 10 pages per page.
for example,I have 14 pieces of data, which should have been one page, but now the totalpage is 2.

I will submit a PR next week.

![image](https://user-images.githubusercontent.com/28941816/142758615-44990008-82d6-4b4c-8dac-1032450189a8.png)

![image](https://user-images.githubusercontent.com/28941816/142758606-7c4ef9ae-aac0-4ea6-a81c-4be59f6f32ff.png)

**Comment by wu-sheng** [comment]
Do you mean a UI side bug? Are you using the latest release?

**Comment by anjoy8** [comment]
Sorry, it's version 8.3. I'll try updating the latest version.
By the way, I use docker image.

**Comment by wu-sheng** [comment]
Docker seems irrelative, but we only follow the issue for the latest release, as SkyWalking has too many enhancements and fixes for every release.
