### ISSUE TITLE
日志进行关键字搜索时并没有传入关键字参数

### ISSUE THREAD

**Issue by mengTnT** [apache/skywalking-rocketbot-ui#563]
![image](https://user-images.githubusercontent.com/30362673/144556931-09d103dd-9695-4aac-81d4-a169d44c4c18.png)

**Comment by mengTnT** [comment]
bug发现的页面：http://demo.skywalking.apache.org/log

**Comment by wu-sheng** [comment]
All things must be in English for global users. Closing.
You need to enter for confirmation.
