### ISSUE TITLE
Skywalking UI not working after update from 8.6.0

### ISSUE THREAD

**Issue by DusanSild** [apache/skywalking-rocketbot-ui#565]
Hello,
we are using Skywalking-OAP and Skywalking-UI docker images, version 8.6, with Postgres storage.
We tried to migrate to 8.9.1 but after update OAP failed on DB column "content-type". I dropped the database on my local machine, then OAP runs fine.
But UI still isn't showing anything, its blank. I checked that tracing and logging data are in DB.

When I revert UI to version 8.6 it works fine, but any newer version doesn't work without any error or log entry. See: [skywalking-ui.log](https://github.com/apache/skywalking-rocketbot-ui/files/7884755/skywalking-ui.log)
Do you have any idea what to check or do?

v8.9.1:
![image](https://user-images.githubusercontent.com/81760659/149839651-e195d787-b441-4332-b1f7-57934f15908a.png)

v8.6.0:
![image](https://user-images.githubusercontent.com/81760659/149839831-746abc56-9262-486f-8efd-21b0a53a469e.png)

**Comment by wu-sheng** [comment]
Clear your browser cache. The UI local cache changes from version to version.

**Comment by DusanSild** [comment]
Yes, I tried already, but it didn't help.

**Comment by wu-sheng** [comment]
Then, your OAP server is not booting successfully.

**Comment by DusanSild** [comment]
It seems OAP server is running fine: [skywalking-oap.log](https://github.com/apache/skywalking-rocketbot-ui/files/7887170/skywalking-oap.log)
No error at all, I can see the data in DB tables.

**Comment by wu-sheng** [comment]
Then, I don't have a clue. If OAP is working, the only thing should be Browser local cache. Otherwise, at least the UI templates should be list correctly, but in your screenshot, you are not.
