### ISSUE TITLE
追踪服务列表筛选时候js会出错

### ISSUE THREAD

**Issue by KBCode** [apache/skywalking-rocketbot-ui#569]
当服务列表有67个服务进行关键字筛选会出现js错误。如果选择一个服务没有错误。
![559F31A9-D18A-4f2d-9743-E35EAEAD2D1C](https://user-images.githubusercontent.com/1418857/155303345-e76e5375-034e-47cc-9668-406cb603380e.png)

**Comment by wu-sheng** [comment]
We only accept English discussion on GitHub. And this UI is going to ve replaced.
