### ISSUE TITLE
Support the trace list or tree display export jpeg or pdf ?

### ISSUE THREAD

**Issue by zxbu** [apache/skywalking-rocketbot-ui#96]
I want to save one trace display as a jpeg or pdf file sometimes, 
I think it is a good feature

**Comment by wu-sheng** [comment]
@TinyAllen If you try to do that, please make sure the license is good, and added.
In my mind, pdf and image features are high-risk licenses.

**Comment by TinyAllen** [comment]
@wu-sheng l will try to do this, but I need to do some research first.

**Comment by wu-sheng** [comment]
@TinyAllen This is not a high priority feature, take your time.

**Comment by wu-sheng** [comment]
Provided.
